### ISSUE TITLE
Deploy to Bluemix fails

### ISSUE THREAD

**Issue by bravera** [gameontext/sample-room-nodejs#9]
Tried deploying this to Bluemix today and it crashes on start up. Tried US and UK.

This is the final extract of the log output...

2017-01-05T12:31:13.83+0000 [CELL/0]     OUT Successfully destroyed container
2017-01-05T12:39:26.90+0000 [CELL/0]     OUT Successfully created container
2017-01-05T12:39:28.49+0000 [CELL/0]     OUT Starting health monitoring of container
2017-01-05T12:39:29.05+0000 [APP/0]      OUT Starting app with 'node  server.js '
2017-01-05T12:39:29.29+0000 [APP/0]      OUT info: Not registering as no valid config is available
2017-01-05T12:39:29.31+0000 [APP/0]      OUT info: The WebSocket server is listening...
2017-01-05T12:40:29.60+0000 [CELL/0]     ERR Timed out after 1m0s: health check never passed.
2017-01-05T12:40:29.61+0000 [CELL/0]     OUT Exit status 0
2017-01-05T12:40:40.66+0000 [API/8]      OUT App instance exited with guid a6c5754e-0bb5-4cf1-bec9-83f1c733089a payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 4\n* 2 error(s) occurred:\n\n* cancelled\n* process did not exit", "crash_count"=>8, "crash_timestamp"=>1483620040614164234, "version"=>"181e2bbd-c391-4a79-86d4-e3b04295247f"}
2017-01-05T12:56:54.62+0000 [CELL/0]     OUT Creating container
2017-01-05T12:57:02.56+0000 [CELL/0]     OUT Successfully created container
2017-01-05T12:57:03.83+0000 [CELL/0]     OUT Starting health monitoring of container
2017-01-05T12:57:04.22+0000 [APP/0]      OUT Starting app with 'node  server.js '
2017-01-05T12:57:04.36+0000 [APP/0]      OUT info: Not registering as no valid config is available
2017-01-05T12:57:04.39+0000 [APP/0]      OUT info: The WebSocket server is listening...
2017-01-05T12:58:05.24+0000 [CELL/0]     ERR Timed out after 1m0s: health check never passed.
2017-01-05T12:58:16.25+0000 [CELL/0]     OUT Destroying container
2017-01-05T12:58:16.90+0000 [CELL/0]     OUT Successfully destroyed container

**Comment by rstephenrrtx** [comment]
I was playing around with the sample also.  While using the "cf push <name>" approach it crashed.  The log is attached.

[sample-room-nodejs.err.txt](https://github.com/gameontext/sample-room-nodejs/files/709575/sample-room-nodejs.err.txt)

First set of errors shows:
2017-01-16T17:20:32.39-0500 [APP/0]      OUT Starting app with 'node  server.js 
2017-01-16T17:20:32.50-0500 [APP/0]      ERR module.js:327
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     throw err;
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     ^
2017-01-16T17:20:32.50-0500 [APP/0]      ERR Error: Cannot find module 'websocket'
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Function.Module._resolveFilename (module.js:325:15)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Function.Module._load (module.js:276:25)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Module.require (module.js:353:17)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at require (internal/module.js:12:17)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Object.<anonymous> (/home/vcap/app/server.js:5:23)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Module._compile (module.js:409:26)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Object.Module._extensions..js (module.js:416:10)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Module.load (module.js:343:32)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Function.Module._load (module.js:300:12)
2017-01-16T17:20:32.50-0500 [APP/0]      ERR     at Function.Module.runMain (module.js:441:10)
